version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
    ignore:
      # Color package uses ES6 syntax from v4+ which is not compatible with our setup
      - dependency-name: "color"
        update-types: ["version-update:semver-major"]
