version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
    ignore:
      # Storybook 6.4 causes issues with the code samples in our stories.
      # A fix and manual update is needed before upgrading.
      - dependency-name: "@storybook/addon-a11y"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "@storybook/addon-docs"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "@storybook/addon-viewport"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "@storybook/html"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "@storybook/theming"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      # Webpack 5 update can only happen after Storybook supports it, we'll need to do a manual upgrade then.
      # For now keep the loader versions compatible with Webpack 4.
      - dependency-name: "css-loader"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass-loader"
        update-types: ["version-update:semver-major"]
      - dependency-name: "style-loader"
        update-types: ["version-update:semver-major"]
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      # Color package uses ES6 syntax from v4+ which is not compatible with our setup
      - dependency-name: "color"
        update-types: ["version-update:semver-major"]
      # Stay at React 16 until React 17 is fully supported by Storybook
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Percy needs a manual upgrade as it doesn't work without breaking
      - dependency-name: "@percy/storybook"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/documentation/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "npm"
    directory: "/components/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
