---
version: "3"
services:
  storybook:
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/.npm
    build:
      args:
        - "NODE_ENV=development"
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "PORT=6006"
    ports:
      - "6006:6006"
    command: "storybook"
